#define DEBUG_ENABLE          0
#define SHOW_REGISTERS        0
#define SINGLE_STEP           0
#define SHOW_STATISTICS       0
#define ASSERT_ENABLE         1

#define DEFAULT_MEMORY_SIZE   0x2000000
#define DEFAULT_CACHE_SIZE    0x10000
#define DEFAULT_STACK_ADDRESS DEFAULT_MEMORY_SIZE
#define DEFAULT_HEAP_ADDRESS  DEFAULT_MEMORY_SIZE
